server:
  port: 80

spring:
  application:
    name: seata-gateway
  #gateway配置
  cloud:
    gateway:
      routes:
        #注意id要和uri平齐
        - id: order_route #payment_route    #路由的ID，没有固定规则但要求唯一，建议配合服务名
          uri: lb://SEATA-ORDER-SERVICE          #匹配后提供服务的路由地址
          predicates:
            - Path=/order/**        # 断言，路径相匹配的进行路由

eureka:
  instance:
    hostname: seata-gateway-service
  client: #服务提供者provider注册进eureka服务列表内
    service-url:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: http://192.168.150.128:7001/eureka